# Generated by Django 3.2.8 on 2021-10-25 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='last_updated',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='shared',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
