# Generated by Django 3.2.8 on 2021-10-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_posts_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='content',
            new_name='addcomment',
        ),
    ]
