# Generated by Django 3.2.8 on 2021-10-26 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_addcomment_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='shared_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.posts'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='shared_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
