# Generated by Django 3.2.8 on 2021-10-26 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20211026_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='shared_post',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='blog.posts'),
        ),
    ]
